name: Poller CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # Set backend as the default working directory for all run steps

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json  # Specify the path to package-lock.json

    - run: npm ci

    - run: npm run lint  # If you have a lint script

    - run: npm run build --if-present

    - run: npm test
